services:
  # outputFrontendTemplate table hook
  Markocupic\PreloaderOverlay\Listener\ContaoHooks\OutputFrontendTemplate:
    tags:
    - { name: contao.hook, hook: outputFrontendTemplate, method: onOutputFrontendTemplate, priority: 0 }
